default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnb_clone_development
  username: postgres  # Remplace par ton nom d'utilisateur PostgreSQL
  password: Koriase05 # Remplace par ton mot de passe PostgreSQL
  host: localhost

test:
  <<: *default
  database: airbnb_clone_test
  username: postgres  # Remplace par ton nom d'utilisateur PostgreSQL
  password: Koriase05 # Remplace par ton mot de passe PostgreSQL
  host: localhost

production:
  <<: *default
  database: airbnb_clone_production
  username: airbnb_clone
  password: <%= ENV['AIRBNB_CLONE_DATABASE_PASSWORD'] %>
  host: localhost
